apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calculater-app-prod
  namespace: argocd
spec:
  project: default
  source:
    path: ./
    repoURL: git@github.com:thitiwutnew/calculater-app-prod.git
    targetRevision: main
    helm:
      releaseName: calculater-app-prod
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-calculator
  syncPolicy:
    automated:
      prune: true