apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calculater-app-nonprod-dev
  namespace: argocd
spec:
  project: default
  source:
    path: ./
    repoURL: git@github.com:thitiwutnew/calculater-app-nonprod.git
    targetRevision: main
    helm:
      releaseName: calculater-app-nonprod-dev
      valueFiles:
        - ./values/dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nonprod-dev
  syncPolicy:
    automated:
      prune: true