apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calculater-app-config-nonprod-uat
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:thitiwutnew/calculater-app-config-nonprod.git
    targetRevision: main
    path: uat
  destination:
    server: https://kubernetes.default.svc
    namespace: nonprod-uat
  syncPolicy:
    automated:
      prune: true