apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calculator-config-nonprd-uat
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:miw1513/k8s-calculator-config-nonprd.git
    targetRevision: main
    path: uat
  destination:
    server: https://kubernetes.default.svc
    namespace: nonprd-uat
  syncPolicy:
    automated:
      prune: true